### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by gastonmourelle** [synterrr/Syn_userInfo#1]
Hey! It looks amazing, but I couldn't make it work yet. I mean, I copied my discord channel webhook into config.lua, and when I test it on my test server it doesn't send me any log in my discord channel. I press F8 and write UInfo 1 (1 is my ID), and nothing...
Hope you can help me because this looks incredible. Cheers!
![Screenshot_4](https://user-images.githubusercontent.com/72710777/125158932-80d1e180-e14a-11eb-8e03-9c902c203c7c.png)
![Screenshot_5](https://user-images.githubusercontent.com/72710777/125158934-816a7800-e14a-11eb-81c5-39c89c84f524.png)
![Screenshot_6](https://user-images.githubusercontent.com/72710777/125158935-82030e80-e14a-11eb-87e4-d820488a0c1a.png)

**Comment by synterrr** [comment]
which framework do you use?

**Comment by gastonmourelle** [comment]
ESX

**Comment by synterrr** [comment]
i didn't made it to work with ESX yet

**Comment by gastonmourelle** [comment]
Ohh ok, would you make it?
